---
- name: Install Apache Web Server
  package:
    name: httpd
    state: present
  become: yes

- name: Generate index.html from jinja2 template and copy to the remote host
  template:
    src: index.html.j2
    dest: "{{ dest_folder }}/index.html"
  notify:
    - Reload Apache
  become: yes
