name: Terraform Validation and Linting

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_run:
    workflows: ["Deploy to Staging", "Deploy to Production"]
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install TFLint
        run: |
          wget https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip
          unzip tflint_linux_amd64.zip
          sudo mv tflint /usr/local/bin/

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Run TFLint
        run: tflint
